[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"
  environment = { NEXT_PUBLIC_API_URL = "https://f1-analytics-production-b1bf.up.railway.app", NEXT_PUBLIC_API_KEY = "754b5a8e5c6c17f92026f9fedbe15bf58fbb0af80c3706098d0da7701327ad26" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
